### ISSUE TITLE
Upgrade to latest prettier-eslint version

### ISSUE THREAD

**Issue by dmacdnld** [danielterwiel/prettier-eslint-webpack-plugin#3]
Hello! Thanks for sharing this plugin. Would it be OK if it had its [prettier-eslint](https://github.com/prettier/prettier-eslint) dependency upgraded to the latest version (4.4.0)? I have submitted a pull request to do so:  #2. If there are any issues with my pull request I would be happy to fix them. Thanks again!

**Comment by danielterwiel** [comment]
Sure thing! Merged. 🙂

**Comment by dmacdnld** [comment]
Thank you! 🙌🏼
